import { AuthProvider } from "@/context/AuthContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen items-center justify-center">
          <div className="w-full max-w-xs">
            <h1 className="mb-2 text-center text-3xl font-bold text-blue-600">
              Login Account
            </h1>
            <p className="mb-8 text-center font-medium text-slate-500">
              Welcome Back !
            </p>
            <AuthProvider>{children}</AuthProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
